apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orchestrator.server.fullname" . }}-database
  labels:
    {{- include "orchestrator.server.labels" . | nindent 4 }}
data:
  POSTGRESQL_HOSTNAME: !!str {{ template "substra-orc.postgresql.host" . }}
  POSTGRESQL_PORT: !!str {{ .Values.postgresql.port }}
  POSTGRESQL_DATABASE: !!str {{ .Values.postgresql.auth.database }}
  POSTGRESQL_CONNECTION_PARAMETERS: !!str {{ template "substra-orc.postgresql.connectionParameters" . }}