apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orchestrator.server.fullname" . }}-env
  labels:
    {{- include "orchestrator.server.labels" . | nindent 4 }}
data:
  # Global settings
  ORCHESTRATOR_VERIFY_CLIENT_MSP_ID: "{{ and $.Values.orchestrator.tls.enabled $.Values.orchestrator.tls.mtls.enabled $.Values.orchestrator.verifyClientMSPID }}"
  ORCHESTRATOR_CHANNEL_CONFIG: /var/orchestrator/config.yaml
  ORCHESTRATOR_TX_RETRY_BUDGET: "{{ .Values.orchestrator.txRetryBudget }}"

  # Standalone settings
  LOG_SQL_VERBOSE: "{{ .Values.orchestrator.logSQLVerbose }}"

  # TLS settings
  ORCHESTRATOR_TLS_ENABLED: "{{ $.Values.orchestrator.tls.enabled }}"
  ORCHESTRATOR_MTLS_ENABLED: "{{ and $.Values.orchestrator.tls.enabled $.Values.orchestrator.tls.mtls.enabled }}"
  {{- if $.Values.orchestrator.tls.enabled }}
  ORCHESTRATOR_TLS_CERT_PATH: /var/orchestrator/tls/server/pair/tls.crt
  ORCHESTRATOR_TLS_KEY_PATH: /var/orchestrator/tls/server/pair/tls.key
  {{- if $.Values.orchestrator.tls.mtls.enabled }}
  ORCHESTRATOR_TLS_SERVER_CA_CERT: /var/orchestrator/tls/server/cacert/ca.crt
  ORCHESTRATOR_TLS_CLIENT_CA_CERT_DIR: /var/orchestrator/tls/client/
  {{- end }}
  {{- end }}
