{{- if eq .Values.orchestrator.mode "distributed" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrator.eventForwarder.fullname" . }}-env
  labels:
    {{- include "orchestrator.eventForwarder.labels" . | nindent 4 }}
data:
  FORWARDER_AMQP_DSN: amqp://{{.Values.rabbitmq.auth.username}}:{{.Values.rabbitmq.auth.password}}@{{ .Release.Name }}-rabbitmq.{{ .Release.Namespace }}:{{.Values.rabbitmq.service.port}}/
  FORWARDER_CONFIG_PATH: /var/hyperledger/forwarder-config.yaml
  
  FORWARDER_FABRIC_CERT: /var/hyperledger/msp/signcerts/cert.pem
  FORWARDER_FABRIC_KEY: /var/hyperledger/msp/keystore/key.pem
  FORWARDER_MSPID: {{ .Values.fabric.mspID }}
  FORWARDER_NETWORK_CONFIG: /var/hyperledger/fabric-config.yaml
{{- end }}
