{{- if eq .Values.orchestrator.mode "distributed" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orchestrator.fullname" . }}-fabric
data:
  fabric-config.yaml: |
    version: 1.0.0
    name: "HLF orchestrator configuration"

    client:
      organization: {{ .Values.fabric.organization }}
      credentialStore:
        cryptoStore:
            path: /tmp  # Without this, the SDK tries to write in $PWD
      tlsCerts:
        systemCertPool: false
        client:
          key:
            path: /var/hyperledger/tls/client/pair/tls.key
          cert:
            path: /var/hyperledger/tls/client/pair/tls.crt
        server:
          key:
            path: /var/hyperledger/tls/server/pair/tls.key
          cert:
            path: /var/hyperledger/tls/server/pair/tls.crt

      logging:
        level: {{ .Values.fabric.logLevel }}

    channels:
      {{- range $channel := .Values.fabric.channels }}
      {{ $channel }}:
        peers:
          {{ $.Values.fabric.peer.host }}:{{ $.Values.fabric.peer.port }}:
            endorsingPeer: true
            eventSource: true
            chaincodeQuery: true
            ledgerQuery: true
        policies:
          eventService:
            # PreferOrg is the default, but let's be explicit
            resolverStrategy: PreferOrg
            # Disable block height filtering so that org's peer will always be preferred, even if they lag behind
            blockHeightLagThreshold: -1
            # Disable peer monitor: we never want to disconnect since we are in a single peer configuration,
            # there wouldn't be any more appropriate peer to connect to.
            peerMonitorPeriod: 0
      {{ end }}

    organizations:
      {{ .Values.fabric.organization }}:
        mspid: {{ .Values.fabric.mspID }}
        peers:
          - {{ .Values.fabric.peer.host }}:{{ .Values.fabric.peer.port }}

    peers:
      {{ .Values.fabric.peer.host }}:{{ .Values.fabric.peer.port }}:
        url: {{ .Values.fabric.peer.host }}:{{ .Values.fabric.peer.port }}
        tlsCACerts:
          path: /var/hyperledger/tls/server/cert/cacert.pem
  {{- end }}
