apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orchestrator.server.fullname" . }}
  labels:
    {{- include "orchestrator.server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "orchestrator.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-env-orchestrator.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orchestrator.server.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "orchestrator.serviceAccountName" . }}
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      initContainers:
      {{- if eq .Values.orchestrator.mode "standalone" }}
      - name: wait-postgresql
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        image: postgres
        command: ['sh', '-c', 'until pg_isready --host={{ template "substra-orc.database.host" . }} --port={{ .Values.database.port }}; do echo "Waiting for postgresql service"; sleep 2; done;']
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: {{ include "substra-orc.images.name" (dict "img" .Values.orchestrator.image "defaultTag" $.Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.orchestrator.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              {{- if eq .Values.orchestrator.mode "standalone" }}
              set -eu
              DATABASE_URI="postgres://$DATABASE_USERNAME:$DATABASE_PASSWORD@$DATABASE_HOSTNAME:$DATABASE_PORT/$DATABASE_DATABASE"
              if [ -n $DATABASE_CONNECTION_PARAMETERS ]; then
                DATABASE_URI="$DATABASE_URI?$DATABASE_CONNECTION_PARAMETERS"
              fi
              export ORCHESTRATOR_DATABASE_URL="$DATABASE_URI"
              {{- end }}
              /app/orchestrator
          ports:
            - name: grpc
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-v"
                - "-addr=:9000"
                {{- if .Values.orchestrator.tls.enabled }}
                - "-tls"
                - "-tls-ca-cert=/var/orchestrator/tls/server/cacert/ca.crt"
                {{- if .Values.ingress.hostname }}
                - "-tls-server-name={{ .Values.ingress.hostname}}" 
                {{- else }}
                - "-tls-server-name={{ include "orchestrator.server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
                {{- end }}
                {{- if .Values.orchestrator.tls.mtls.enabled }}
                - "-tls-client-key=/var/orchestrator/tls/server/pair/tls.key"
                - "-tls-client-cert=/var/orchestrator/tls/server/pair/tls.crt"
                {{- end }}
                {{- end }}
            periodSeconds: 10
            timeoutSeconds: 2
          startupProbe:
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-v"
                - "-addr=:9000"
               {{- if $.Values.orchestrator.tls.enabled }}
                - "-tls"
                - "-tls-ca-cert=/var/orchestrator/tls/server/cacert/ca.crt"
                {{- if .Values.ingress.hostname }}
                - "-tls-server-name={{ .Values.ingress.hostname}}" 
                {{- else }}
                - "-tls-server-name={{ include "orchestrator.server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
                {{- end }}
                {{- if $.Values.orchestrator.tls.mtls.enabled }}
                - "-tls-client-key=/var/orchestrator/tls/server/pair/tls.key"
                - "-tls-client-cert=/var/orchestrator/tls/server/pair/tls.crt"
                {{- end }}
                {{- end }}
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ template "orchestrator.server.fullname" . }}-env
            {{- if eq .Values.orchestrator.mode "standalone" }}
            - configMapRef:
                name: {{ template "orchestrator.server.fullname" . }}-database
            - secretRef:
                name: {{ template "substra-orc.database.secret-name" . }}
            {{- end }}
          env:
           - name: LOG_LEVEL
             value: {{ .Values.orchestrator.logLevel | default "INFO" }}
           {{- if .Values.metrics.enabled }}
           - name: METRICS_ENABLED
             value: "true"
           {{- end }}
          volumeMounts:
            - name: orchestrator-config
              mountPath: /var/orchestrator/config.yaml
              subPath: config.yaml
              readOnly: true
            {{- if eq .Values.orchestrator.mode "distributed" }}
            - name: fabric-config
              mountPath: /var/hyperledger/fabric-config.yaml
              subPath: fabric-config.yaml
            - name: user-cert
              mountPath: /var/hyperledger/msp/signcerts
            - name: user-key
              mountPath: /var/hyperledger/msp/keystore
            - name: peer-tls-server
              mountPath: /var/hyperledger/tls/server/pair
            - name: peer-tls-client
              mountPath: /var/hyperledger/tls/client/pair
            - name: cacert
              mountPath: /var/hyperledger/tls/server/cert/
            {{- end }}
            {{- if $.Values.orchestrator.tls.enabled }}
            - name: orchestrator-tls-server-pair
              mountPath: /var/orchestrator/tls/server/pair
              readOnly: true
            - name: orchestrator-tls-cacert
              mountPath: /var/orchestrator/tls/server/cacert
              readOnly: true
            {{- if $.Values.orchestrator.tls.mtls.enabled }}
            {{- range $org, $secret := $.Values.orchestrator.tls.mtls.clientCACerts }}
            - name: orchestrator-tls-client-cacert-{{ kebabcase $org }}
              mountPath: /var/orchestrator/tls/client/{{ $org }}
              readOnly: true
            {{- end }}
            {{- end }}
            {{- end }}
      volumes:
        - name: orchestrator-config
          configMap:
            name: {{ template "orchestrator.server.fullname" . }}-config
            items:
              - key: "config.yaml"
                path: "config.yaml"
        {{- if eq .Values.orchestrator.mode "distributed" }}
        - name: user-cert
          secret:
            secretName: {{ $.Values.fabric.secrets.user.cert }}
        - name: user-key
          secret:
            secretName: {{ $.Values.fabric.secrets.user.key }}
        - name: peer-tls-server
          secret:
            secretName: {{ $.Values.fabric.secrets.peer.tls.server }}
        - name: peer-tls-client
          secret:
            secretName: {{ $.Values.fabric.secrets.peer.tls.client }}
        - name: cacert
          secret:
            secretName: {{ $.Values.fabric.secrets.caCert }}
        - name: fabric-config
          configMap:
            name: {{ include "orchestrator.fullname" . }}-fabric
        {{- end }}
        {{- if $.Values.orchestrator.tls.enabled }}
        - name: orchestrator-tls-cacert
          configMap:
            name: {{ $.Values.orchestrator.tls.cacert }}
        - name: orchestrator-tls-server-pair
          secret:
            secretName: {{ $.Values.orchestrator.tls.secrets.pair }}
        {{- if $.Values.orchestrator.tls.mtls.enabled }}
        {{- range $org, $cacerts := $.Values.orchestrator.tls.mtls.clientCACerts }}
        - name: orchestrator-tls-client-cacert-{{ kebabcase $org }}
          projected:
            sources:
              {{- range $cert := $cacerts }}
              - configMap:
                  name: {{ $cert }}
                  items:
                    - key: ca.crt
                      path: {{ kebabcase $cert }}.crt
              {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
