{{- if eq .Values.orchestrator.mode "standalone" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "orchestrator.migrations.fullname" . }}
  labels:
    {{- include "orchestrator.migrations.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "orchestrator.migrations.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      initContainers:
      {{- if .Values.postgresql.enabled }}  {{/* TODO: enable for external pg instances too */}}
      - name: wait-postgresql
        image: busybox
        command: ['sh', '-c', 'until nc -vz {{ template "postgresql.serviceName" . }}.{{ .Release.Namespace }} {{ .Values.postgresql.primary.service.ports.postgresql }}; do echo "Waiting for postgresql service"; sleep 2; done;']
      {{- end }}
      containers:
      - name: db-migrations
        image: {{ include "common.images.name" .Values.orchestrator.image }}
        command: ['sh', '-c',  'migrate -source file:///migrations/ -database "${ORCHESTRATOR_DATABASE_URL}" up']
        envFrom:
        - secretRef:
            name: {{ template "orchestrator.server.fullname" . }}-secret
{{- end }}
