apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "orchestrator.name" . }}-server
spec:
  podSelector:
    matchLabels:
      {{- include "orchestrator.server.labels" . | nindent 10 }}
  policyTypes:
  - Ingress
  ingress:
    # Allow communication from internet
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
          - 10.0.0.0/8
          - 192.168.0.0/16
          - 172.16.0.0/20
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80

