apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "orchestrator.name" . }}-server
spec:
  podSelector:
    matchLabels:
      {{- include "orchestrator.server.labels" . | nindent 10 }}
  policyTypes:
  - Ingress
  ingress:
    # Allow communication from internet, local address ranges are used for inter cluster communication in cloud provider
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: {{ .Values.service.port }}

