apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "orchestrator.server.fullname" . }}-secret
stringData:
  {{- if .Values.postgresql.enabled }}
  ORCHESTRATOR_DATABASE_URL: postgresql://{{ .Values.postgresql.auth.username}}:{{ .Values.postgresql.auth.password}}@{{ template "postgresql.serviceName" . }}.{{ .Release.Namespace }}:{{ .Values.postgresql.primary.service.ports.postgresql }}/{{ .Values.postgresql.auth.database}}?sslmode=disable
  {{- end }}
