apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "orchestrator.server.fullname" . }}-secret
stringData:
  {{- if .Values.postgresql.enabled }}
  ORCHESTRATOR_DATABASE_URL: postgresql://{{ .Values.postgresql.postgresqlUsername}}:{{ .Values.postgresql.postgresqlPassword}}@{{ template "postgresql.serviceName" . }}.{{ .Release.Namespace }}:{{ .Values.postgresql.service.port}}/{{ .Values.postgresql.postgresqlDatabase}}?sslmode=disable
  {{- end }}
