{{- if (and
  (eq .Values.orchestrator.mode "standalone")
  (not .Values.database.auth.credentialsSecretName)
) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "substra-orc.database.secret-name" . }}
  labels:
    {{- include "orchestrator.server.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.database.auth.password | quote }}
  DATABASE_USERNAME: {{ .Values.database.auth.username | quote }}
{{- end }}