{{- if not .Values.postgresql.auth.credentialsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "substra-orc.postgresql.secret-name" . }}
  labels:
    {{- include "orchestrator.server.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRESQL_USERNAME: {{ .Values.postgresql.auth.username | quote }}
{{- end }}