apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "orchestrator.server.fullname" . }}-secret
stringData:
  {{- if eq .Values.orchestrator.mode "standalone" }}
  ORCHESTRATOR_DATABASE_URL: postgresql://{{ .Values.postgresql.auth.username}}:{{ .Values.postgresql.auth.password}}@{{ template "substra-orc.postgresql.host" . }}:{{ template "substra-orc.postgresql.port" . }}/{{ .Values.postgresql.auth.database }}{{ template "substra-orc.postgresql.uriParams" . }}
  {{- end }}
