apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator.server.fullname" . }}
  labels:
    {{- include "orchestrator.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      name: grpc
    {{- if .Values.metrics.enabled }}
    - port: 8484
      targetPort: 8484
      protocol: TCP
      name: metrics 
    {{- end }}
  selector:
    {{- include "orchestrator.server.selectorLabels" . | nindent 4 }}
