run:
  timeout: 2m
linters:
  enable:
    - revive
    - gofmt
    - importas
    - rowserrcheck
    - gosec
    - gocritic

linters-settings:
  importas:
    "orcerrors": github.com/substra/orchestrator/lib/errors
    "commonserv": github.com/substra/orchestrator/server/common
    "sq": github.com/Masterminds/squirrel
    "e2erequire": github.com/substra/orchestrator/e2e/require
