run:
  timeout: 2m
linters:
  enable:
    - revive
    - gofmt
    - importas
    - rowserrcheck

linters-settings:
  importas:
    "orcerrors": github.com/owkin/orchestrator/lib/errors
    "commonserv": github.com/owkin/orchestrator/server/common
