run:
  timeout: 2m
linters:
  enable:
    - golint
    - gofmt
    - importas
    - rowserrcheck

linters-settings:
  golint:
    min-confidence: 0
  importas:
    "orcerrors": github.com/owkin/orchestrator/lib/errors
