---
name: "local hlf network"
description: "dev network"
version: "1.0"

client:
  organization: "MyOrg1"
  tlsCerts:
    systemCertPool: false
    client:
      key:
        path: crypto/org-1/tls/client/pair/tls.key
      cert:
        path: crypto/org-1/tls/client/pair/tls.crt
    # server:
    #   key:
    #     path: crypto/org-1/tls/server/pair/tls.key
    #   cert:
    #     path: crypto/org-1/tls/server/pair/tls.crt

channels:
  mychannel:
    peers:
      localhost:7051:
        endorsingPeer: true
        eventSource: true
        chaincodeQuery: true
        ledgerQuery: true
    # orderers:
    #   - orderer.example.org

organizations:
  MyOrg1:
    mspid: "MyOrg1MSP"
    peers:
      - localhost:7051

# orderers:
#   orderer.example.org:
#     url: localhost:7050

peers:
  localhost:7051:
    url: localhost:7051
    tlsCACerts:
      path: crypto/org-1/tls/server/cert/cacert.pem
    # grpcOptions:
    #   ssl-target-name-override: network-org-1-peer-1-hlf-peer.org-1
    #   keep-alive-time: 0s
    #   keep-alive-timeout: 20s
    #   keep-alive-permit: false
    #   fail-fast: false
    #   allow-insecure: false
