apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: owkin/orchestrator
      context: .
      docker:
        dockerfile: docker/server/Dockerfile
    - image: owkin/forwarder
      context: .
      docker:
        dockerfile: docker/forwarder/Dockerfile
deploy:
  helm:
    releases:
      - name: owkin-orchestrator-org-1
        chartPath: charts/orchestrator
        namespace: org-1
        createNamespace: true
        artifactOverrides:
          orchestrator.image: owkin/orchestrator
          forwarder.image: owkin/forwarder
        imageStrategy:
          helm: {}
        valuesFiles: [ examples/values/orchestrator-org-1.yaml ]
      - name: owkin-orchestrator-org-2
        chartPath: charts/orchestrator
        namespace: org-2
        createNamespace: true
        artifactOverrides:
          orchestrator.image: owkin/orchestrator
          forwarder.image: owkin/forwarder
        imageStrategy:
          helm: {}
        valuesFiles: [ examples/values/orchestrator-org-2.yaml ]

  kubectl:
    manifests:
      - examples/secrets/secret-tls-org-1-cacert.yaml
      - examples/secrets/secret-tls-org-1-server-pair.yaml
      - examples/secrets/secret-tls-org-2-cacert.yaml
      - examples/secrets/secret-tls-org-2-server-pair.yaml

profiles:
  # Only org1 in standalone mode
- name: solo
  activation:
    - env: ORCHESTRATOR_MODE=  # env variable is empty/missing,
  patches:
    - op: remove
      path: /deploy/helm/releases/1
    - op: remove
      path: /deploy/kubectl/manifests/3

- name: chaincode
  activation:
    - env: ORCHESTRATOR_MODE=chaincode
  patches:
    - op: replace
      path: /deploy/helm/releases/0/valuesFiles
      value: [ examples/values/orchestrator-org-1-chaincode.yaml ]
    - op: replace
      path: /deploy/helm/releases/1/valuesFiles
      value: [ examples/values/orchestrator-org-2-chaincode.yaml ]
