apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: owkin/orchestrator
      context: .
      docker:
        dockerfile: Dockerfile.orchestrator
deploy:
  helm:
    releases:
      - name: owkin-orchestrator-org-1
        chartPath: charts/orchestrator
        namespace: org-1
        artifactOverrides:
          image: owkin/orchestrator
        imageStrategy:
          helm: {}
        setValues:
          orchestrator.mode: chaincode
          fabric.organization: MyOrg1
          fabric.mspID: MyOrg1MSP
          fabric.peer.host: network-org-1-peer-1-hlf-peer.org-1
      - name: owkin-orchestrator-org-2
        chartPath: charts/orchestrator
        namespace: org-2
        artifactOverrides:
          image: owkin/orchestrator
        imageStrategy:
          helm: {}
        setValues:
          orchestrator.mode: chaincode
          fabric.organization: MyOrg2
          fabric.mspID: MyOrg2MSP
          fabric.peer.host: network-org-2-peer-1-hlf-peer.org-2
