apiVersion: skaffold/v4beta2
kind: Config
requires:
- configs:
  - cert_manager
build:
  artifacts:
  - image: substra/orchestrator-server
    context: .
    docker:
      dockerfile: docker/orchestrator-server/Dockerfile
manifests:
  helm:
    releases:
    - name: orchestrator-org-1
      chartPath: charts/orchestrator
      valuesFiles:
      - examples/values/orchestrator-org-1.yaml
      namespace: org-1
      setValueTemplates:
        orchestrator.image.registry: '{{.IMAGE_DOMAIN_substra_orchestrator_server}}'
        orchestrator.image.repository: '{{.IMAGE_REPO_NO_DOMAIN_substra_orchestrator_server}}'
        orchestrator.image.tag: '{{.IMAGE_TAG_substra_orchestrator_server}}@{{.IMAGE_DIGEST_substra_orchestrator_server}}'
      createNamespace: true
      skipBuildDependencies: true
  hooks:
    before:
      - host:
          # `skaffold run` does not update chart dependencies:
          # https://github.com/GoogleContainerTools/skaffold/issues/5445
          # So we update the dependencies ourselves.
          command:
          - 'helm'
          - 'dep'
          - 'build'
          - 'charts/orchestrator'
          os: [darwin, linux]
deploy:
  helm: {}
profiles:
- name: distributed
  patches:
  - op: replace
    path: /manifests/helm/releases/0/valuesFiles
    value:
    - examples/values/orchestrator-org-1-distributed.yaml
  - op: add
    path: /manifests/helm/releases/-
    value:
      setValueTemplates:
        orchestrator.image.registry: '{{.IMAGE_DOMAIN_substra_orchestrator_server}}'
        orchestrator.image.repository: '{{.IMAGE_REPO_NO_DOMAIN_substra_orchestrator_server}}'
        orchestrator.image.tag: '{{.IMAGE_TAG_substra_orchestrator_server}}@{{.IMAGE_DIGEST_substra_orchestrator_server}}'
      chartPath: charts/orchestrator
      createNamespace: true
      name: orchestrator-org-2
      namespace: org-2
      skipBuildDependencies: true
      valuesFiles:
      - examples/values/orchestrator-org-2-distributed.yaml
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: certificates
requires:
- configs:
  - cert_manager
manifests:
  rawYaml:
  - examples/k8s/cm-tls-org-1-cacert.yaml
  - examples/k8s/secret-cacert-certmanager.yaml
  - examples/k8s/certmanagerca.yaml
  - examples/k8s/cm-tls-org-2-cacert.yaml
deploy:
  kubectl: {}
profiles:
- name: apponly
  patches:
  - op: remove
    path: /manifests/rawYaml
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: cert_manager
manifests:
  helm:
    releases:
    - name: cert-manager
      remoteChart: jetstack/cert-manager
      namespace: cert-manager
      version: v1.9.1
      createNamespace: true
deploy:
  helm:
    hooks:
      before:
      - host:
          command:
          - sh
          - -c
          - kubectl apply --context=${SKAFFOLD_KUBE_CONTEXT} -f https://github.com/jetstack/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml
profiles:
- name: apponly
  patches:
  - op: remove
    path: /manifests/helm
