apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: substrafoundation/orchestrator
      context: .
      docker:
        dockerfile: docker/server/Dockerfile
    - image: substrafoundation/rabbitmq-operator
      context: .
      docker:
        dockerfile: docker/rabbitmq-operator/Dockerfile
deploy:
  helm:
    releases:
      - name: owkin-orchestrator-org-1
        chartPath: charts/orchestrator
        namespace: org-1
        createNamespace: true
        artifactOverrides:
          orchestrator.image: substrafoundation/orchestrator
          rabbitmqOperator.image: substrafoundation/rabbitmq-operator
        imageStrategy:
          helm: {}
        valuesFiles: [ examples/values/orchestrator-org-1.yaml ]

  kubectl:
    manifests:
      - examples/secrets/secret-tls-org-1-cacert.yaml
      - examples/secrets/secret-tls-org-1-server-pair.yaml
      - examples/secrets/secret-tls-org-2-cacert.yaml

profiles:
- name: distributed
  patches:
  - op: add
    path: "/build/artifacts/-"
    value:
      image: substrafoundation/forwarder
      context: .
      docker:
        dockerfile: docker/forwarder/Dockerfile
  - op: replace
    path: /deploy/helm/releases/0/valuesFiles
    value: [ examples/values/orchestrator-org-1-distributed.yaml ]
  - op: replace
    path: /deploy/helm/releases/0/artifactOverrides
    value:
      orchestrator.image: substrafoundation/orchestrator
      forwarder.image: substrafoundation/forwarder
      rabbitmqOperator.image: substrafoundation/rabbitmq-operator
  - op: add
    path: "/deploy/helm/releases/-"
    value:
      name: owkin-orchestrator-org-2
      chartPath: charts/orchestrator
      namespace: org-2
      createNamespace: true
      artifactOverrides:
        orchestrator.image: substrafoundation/orchestrator
        forwarder.image: substrafoundation/forwarder
        rabbitmqOperator.image: substrafoundation/rabbitmq-operator
      imageStrategy:
        helm: {}
      valuesFiles: [ examples/values/orchestrator-org-2-distributed.yaml ]
      skipBuildDependencies: true # deps already built by other release (org-1)
  - op: add
    path: "/deploy/kubectl/manifests/-"
    value:
      examples/secrets/secret-tls-org-2-server-pair.yaml
- name: nodeps
  patches:
    - op: add
      path: /deploy/helm/releases/0/skipBuildDependencies
      value: true
