apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: owkin/orchestrator
      context: .
      docker:
        dockerfile: docker/server/Dockerfile
    - image: owkin/forwarder
      context: .
      docker:
        dockerfile: docker/forwarder/Dockerfile
    - image: owkin/rabbitmq-operator
      context: .
      docker:
        dockerfile: docker/rabbitmq-operator/Dockerfile
deploy:
  helm:
    releases:
      - name: owkin-orchestrator-org-1
        chartPath: charts/orchestrator
        namespace: org-1
        createNamespace: true
        artifactOverrides:
          orchestrator.image: owkin/orchestrator
          forwarder.image: owkin/forwarder
          rabbitmqOperator.image: owkin/rabbitmq-operator
        imageStrategy:
          helm: {}
        valuesFiles: [ examples/values/orchestrator-org-1.yaml ]

  kubectl:
    manifests:
      - examples/secrets/secret-tls-org-1-cacert.yaml
      - examples/secrets/secret-tls-org-1-server-pair.yaml
      - examples/secrets/secret-tls-org-2-cacert.yaml

profiles:
- name: distributed
  patches:
    - op: replace
      path: /deploy/helm/releases/0/valuesFiles
      value: [ examples/values/orchestrator-org-1-distributed.yaml ]
    - op: add
      path: "/deploy/helm/releases/-"
      value:
        name: owkin-orchestrator-org-2
        chartPath: charts/orchestrator
        namespace: org-2
        createNamespace: true
        artifactOverrides:
          orchestrator.image: owkin/orchestrator
          forwarder.image: owkin/forwarder
          rabbitmqOperator.image: owkin/rabbitmq-operator
        imageStrategy:
          helm: {}
        valuesFiles: [ examples/values/orchestrator-org-2-distributed.yaml ]
    - op: add
      path: "/deploy/kubectl/manifests/-"
      value:
        examples/secrets/secret-tls-org-2-server-pair.yaml
