apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: debug-client-cert
  namespace: org-1
spec:
  secretName: orchestrator-client-cert
  duration: 2160h
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - MyOrg1MSP
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - substra-backend.node-1.com
  issuerRef:
    name: owkin-issuer
    kind: ClusterIssuer
