apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEUTCCAzmgAwIBAgIJALRkAuZ5x+Q+MA0GCSqGSIb3DQEBCwUAMHcxCzAJBgNV
    BAYTAkZSMRkwFwYDVQQIDBBMb2lyZS1BdGxhbnRpcXVlMQ8wDQYDVQQHDAZOYW50
    ZXMxHTAbBgNVBAoMFE9yY2hlc3RyYXRvciBSb290IENBMR0wGwYDVQQDDBRPcmNo
    ZXN0cmF0b3IgUm9vdCBDQTAeFw0yMTEwMjgxNDE4MzhaFw0yMjEwMjgxNDE4Mzha
    MHcxCzAJBgNVBAYTAkZSMRkwFwYDVQQIDBBMb2lyZS1BdGxhbnRpcXVlMQ8wDQYD
    VQQHDAZOYW50ZXMxHTAbBgNVBAoMFE9yY2hlc3RyYXRvciBSb290IENBMR0wGwYD
    VQQDDBRPcmNoZXN0cmF0b3IgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBALEUGlFznr1BCsny65lQos/3MiLC8gFT8S31tXyMrMbcweYzZOAP
    Lt+bx3es+xu8SXp9hXXRCHXTMnnAP9B25L5HrghzzThQ+xCY1pAm8csxl2es9Vqg
    9fJm7Ko6Q1+ApPpY+LR4lpujWhao5HEvBWk1mDXWp7VtXT66sr7kixApKQcSiL4Q
    fpsetF8wx9kE6HRQyJw8NgDm3fjmJIkxRL6CTr8QsBEulKRn5hQehmHpuapp8F+o
    Z4M4DkV6LjfHUHDl/pbvpXuvwZS+ogtJkrispO+1C1XhUcGkVp437/yiE9PD/V2J
    us/kGerC0Wd8wR01q/rzbwxwCPXrysCqinkCAwEAAaOB3zCB3DAPBgNVHRMBAf8E
    BTADAQH/MB0GA1UdDgQWBBR8H2eTgcyoX4e1oL3/ioCJRDDH4TCBqQYDVR0jBIGh
    MIGegBR8H2eTgcyoX4e1oL3/ioCJRDDH4aF7pHkwdzELMAkGA1UEBhMCRlIxGTAX
    BgNVBAgMEExvaXJlLUF0bGFudGlxdWUxDzANBgNVBAcMBk5hbnRlczEdMBsGA1UE
    CgwUT3JjaGVzdHJhdG9yIFJvb3QgQ0ExHTAbBgNVBAMMFE9yY2hlc3RyYXRvciBS
    b290IENBggkAtGQC5nnH5D4wDQYJKoZIhvcNAQELBQADggEBAKw8xgO8JF4aEvBU
    FaXuYfxZ4TUljcKYyB4RD7TZ4G4RgYNcDTSGvsf+uJQWjPsfxisvLFiKp9MAXff1
    Km7Z2U+kYqmleMsHrP0vsUkaJh4guCUWKYcYoi/viw4TMTBuGjagp+gEtO+pTyX/
    Ice0a2AwTVM3mPh77592XGJbkdclFdgizzaKkcPIVSptu/kMCRfmJy02U8QkYgUl
    8+Ki1tVcxJZYgit5m23BnCl05+fgStU1x47U2pD+PNhiy8/0Y+M8wGfDCCtNyRd3
    OsVl3fVPZQwBz6Lszyl9iXESJIMXTCsDEatd9gsPCpRL71/jbwFAkmvTwH5pdU53
    FvQBsiQ=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: orchestrator-tls-cacert
  namespace: org-2
