apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEUTCCAzmgAwIBAgIJAKpdIcXefHK3MA0GCSqGSIb3DQEBCwUAMHcxCzAJBgNV
    BAYTAkZSMRkwFwYDVQQIDBBMb2lyZS1BdGxhbnRpcXVlMQ8wDQYDVQQHDAZOYW50
    ZXMxHTAbBgNVBAoMFE9yY2hlc3RyYXRvciBSb290IENBMR0wGwYDVQQDDBRPcmNo
    ZXN0cmF0b3IgUm9vdCBDQTAeFw0yMjExMTcxMTA0MzNaFw0yMzExMTcxMTA0MzNa
    MHcxCzAJBgNVBAYTAkZSMRkwFwYDVQQIDBBMb2lyZS1BdGxhbnRpcXVlMQ8wDQYD
    VQQHDAZOYW50ZXMxHTAbBgNVBAoMFE9yY2hlc3RyYXRvciBSb290IENBMR0wGwYD
    VQQDDBRPcmNoZXN0cmF0b3IgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAN7vb1LVqT3HVJMxFvDTMS9Kl8MYIOgkMz0ZVi1mRKsCLvk65iIg
    3vE0QUhBfh/lw7PEiGbGHh3i51TAPTRq0tJvu2dyUPGWyrbXfRZp9TFlDM5UTKml
    lRduu9qbFDdgJEmluvLVs/OYHP3tNr1SRzDqnP+8WWxrRAmHi4Pw0TLbPsN8iFGu
    m2Dx+PV/L5B5UwTD3nWCK11ZhAd+2BxAFeQ96v8APiLkurrF7BCt53Fv37Q6AEY0
    yE9QevO6r/08P8cbr3SuPMn1NV1Gf/ltR7BZ5BPbjN+2KBO5GX2ht+AI1NKRX7vg
    WhWj7rxBrN1d++xkdI702Ch0O7utgccI/UcCAwEAAaOB3zCB3DAPBgNVHRMBAf8E
    BTADAQH/MB0GA1UdDgQWBBQw1Tdwxo0f/XqBh9VEUmI0g4bDfjCBqQYDVR0jBIGh
    MIGegBQw1Tdwxo0f/XqBh9VEUmI0g4bDfqF7pHkwdzELMAkGA1UEBhMCRlIxGTAX
    BgNVBAgMEExvaXJlLUF0bGFudGlxdWUxDzANBgNVBAcMBk5hbnRlczEdMBsGA1UE
    CgwUT3JjaGVzdHJhdG9yIFJvb3QgQ0ExHTAbBgNVBAMMFE9yY2hlc3RyYXRvciBS
    b290IENBggkAql0hxd58crcwDQYJKoZIhvcNAQELBQADggEBABFuu2M+aFKl7IIK
    EwSidpjz7b8pUOElJaoxm0Cotohu0PocUn3B/JxvBXYKiflTwqAvEHJZiuudMZuo
    7NYTscrHm48umAEpL9qr8vpdHxeLUwbdr0uYTX3JP2huptArs47elMmXq1gEa4AM
    2acKRvb9+bTIjRm0pPVK9NgEFe4b9yKts8RJZoZm4w93B/Vhn5r6FpbCNdxe082n
    MKNJm2nMsG9UHmCUyC5h7T6h9VnFl61CAA9QMaSDzV2OVp0DDQLMBn7rvELueygw
    2PTvj7Z0jpkRF5uR6zeMV/eC8sEwowk/dQO7Hq9TZjH3Ihi4x8fMdExyh4RwciBi
    4zsdsE0=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: orchestrator-tls-cacert
  namespace: org-1
