@startuml
object "orchestrator" as os
Note top of os: standalone server


object "gRPC server" as grpc
object "AssetServices" as services
note right of services
business logic
end note

object "Persistence layer" as db

os --> grpc
grpc --> services
services --> db

note right of db
multiple backends
end note

@enduml
