@startuml

actor backend
database broker order 90

backend -> orchestrator: gRPC request
' first event
orchestrator --> dispatcher: Push event
dispatcher --> dispatcher: store event
orchestrator <-- dispatcher
' second event
orchestrator --> dispatcher: Push event
dispatcher --> dispatcher: store event
orchestrator <-- dispatcher
orchestrator --> dispatcher: dispatch
dispatcher --> broker: push event
dispatcher <-- broker: confirmed
dispatcher --> broker: push event
dispatcher <-- broker: confirmed
orchestrator <-- dispatcher
backend <- orchestrator: response

@enduml