@startuml

usecase oe as "Orchestration event
--
containing a routing key
based on its channel
"

orchestration << exchange >>
mychannel << exchange >>
yourchannel << exchange >>
backend1 << queue >>
backend2 << queue >>

(oe) -> (orchestration)

note right of orchestration
  messages are dispatched in
  the exchange matching their channel.
end note

(orchestration) --> (mychannel)
(orchestration) --> (yourchannel)

(mychannel) --> (backend1)
(mychannel) --> (backend2)
(yourchannel) --> (backend1)
(yourchannel) --> (backend2)

note right of backend1
  Queues receive events for multiple channels.
  Backends only have access to their dedicated queue
  enforcing isolation between channels.
end note

@enduml