erDiagram
        algos {
                uuid 		id
                varchar-100 	channel
                jsonb 		asset
        }

        compute_plans {
                uuid 		id
                varchar-100 	channel
                jsonb 		asset
        }

        compute_task_parents {
                uuid 	child_task_id
                uuid 	parent_task_id
                integer position
        }

        compute_task_parents ||--o{ compute_tasks : parents
        compute_task_parents ||--o{ compute_tasks : childs

        compute_tasks {
                uuid 		id
                varchar-100 	channel
                jsonb 		asset
                uuid 		compute_plan_key
                varchar-100 	status
                varchar-100 	category
                varchar-100 	worker
        }
  
  	datamanagers {
		uuid 		id
		varchar-100 	channel
		jsonb 		jsonb
	}

	datasamples {
		uuid 		id
		varchar-100 	channel
		jsonb 		asset
	}

	events {
		uuid 		id
		varchar-100 	asset_key
		varchar-100 	channel
		jsonb 		event
	}

	failure_reports {
		uuid 		compute_task_id
		varchar-100 	channel
		jsonb 		asset
	}

	failure_reports ||--o| compute_tasks : documents

	metrics {
		uuid 		id
		varchar-100 	channel
		jsonb 		asset
	}

	models {
		uuid 		id
		varchar-100 	channel
		jsonb 		asset
		uuid 		compute_task_id
	}

	models ||--o{ compute_tasks : output

	nodes {
		varchar-100 	id
		varchar-100 	channel
		jsonb 		asset
	}

	performances {
		uuid 		compute_task_id
		uuid 		metric_id
		varchar-100 	channel
		jsonb 		asset
	}

	performances ||--o{ metrics : compute
	performances ||--o{ compute_tasks : evaluate

