DROP FUNCTION IF EXISTS execute(TEXT);
DROP FUNCTION IF EXISTS schema_exists(TEXT);
DROP FUNCTION IF EXISTS table_exists(TEXT, TEXT);
DROP FUNCTION IF EXISTS view_exists(TEXT, TEXT);
DROP FUNCTION IF EXISTS column_exists(TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS index_exists(TEXT);
