stateDiagram-v2
    WAITING --> TODO
    WAITING --> CANCELED
    WAITING --> FAILED
    TODO --> FAILED
    TODO --> DOING
    TODO --> CANCELED
    DOING --> FAILED
    DOING --> DONE
    DOING --> CANCELED
    DONE --> [*]
    FAILED --> [*]
    CANCELED --> [*]
