graph LR
%% Nodes definition
start((Start))

input_valid{{Input is valid}}
err_input_valid[Error]

dm_query(Get DataManager)
err_dm_query[Error]

perm_check{{Check permissions}}
err_perm_check[Error]

obj_exists{{Objective exists}}
err_obj_exists[Error]

obj_owner{{Owner can download Objective}}
err_obj_owner[Error]

update_dm(Set Objective key)

store_dm(Store dataManager)

End1((End))

%% Dependency graph
start --> input_valid

input_valid --yes--> dm_query
input_valid --no--> err_input_valid

dm_query --exists--> perm_check
dm_query --unknown--> err_dm_query

perm_check --authorized--> obj_exists
perm_check --unauthorized --> err_perm_check

obj_exists --yes--> obj_owner
obj_exists --no--> err_obj_exists

obj_owner --yes--> update_dm
obj_owner --no--> err_obj_owner

update_dm --> store_dm
store_dm --> End1


%% Style
classDef default fill:#5b6fb3,color:#ffffff;
classDef startEnd fill:#C961A1,color:#ffffff;
classDef error fill:#ffab40,color:#ffffff;

class start,End1 startEnd;
class err_input_valid,err_dm_query,err_perm_check,err_obj_exists,err_obj_owner error;
