apiVersion: v2
name: orchestrator
description: substra orchestration

type: application
version: 7.4.5
appVersion: 0.29.0
kubeVersion: ">= 1.19.0-0"
icon: https://avatars.githubusercontent.com/u/84009910?s=400

keywords:
  - substra

sources:
  - https://github.com/Substra/orchestrator/

maintainers:
  - email: alexandre.picosson@owkin.com
    name: Alexandre Picosson
  - email: matthieu.blottiere@owkin.com
    name: Matthieu Blottière

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.6.2
    condition: postgresql.enabled
