// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package objective

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ObjectiveServiceClient is the client API for ObjectiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObjectiveServiceClient interface {
	RegisterObjective(ctx context.Context, in *Objective, opts ...grpc.CallOption) (*Objective, error)
	QueryObjectives(ctx context.Context, in *ObjectiveQueryParam, opts ...grpc.CallOption) (*ObjectiveQueryResponse, error)
	GetLeaderboard(ctx context.Context, in *LeaderboardQueryParam, opts ...grpc.CallOption) (*Leaderboard, error)
}

type objectiveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectiveServiceClient(cc grpc.ClientConnInterface) ObjectiveServiceClient {
	return &objectiveServiceClient{cc}
}

func (c *objectiveServiceClient) RegisterObjective(ctx context.Context, in *Objective, opts ...grpc.CallOption) (*Objective, error) {
	out := new(Objective)
	err := c.cc.Invoke(ctx, "/objective.ObjectiveService/RegisterObjective", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectiveServiceClient) QueryObjectives(ctx context.Context, in *ObjectiveQueryParam, opts ...grpc.CallOption) (*ObjectiveQueryResponse, error) {
	out := new(ObjectiveQueryResponse)
	err := c.cc.Invoke(ctx, "/objective.ObjectiveService/QueryObjectives", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectiveServiceClient) GetLeaderboard(ctx context.Context, in *LeaderboardQueryParam, opts ...grpc.CallOption) (*Leaderboard, error) {
	out := new(Leaderboard)
	err := c.cc.Invoke(ctx, "/objective.ObjectiveService/GetLeaderboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectiveServiceServer is the server API for ObjectiveService service.
// All implementations must embed UnimplementedObjectiveServiceServer
// for forward compatibility
type ObjectiveServiceServer interface {
	RegisterObjective(context.Context, *Objective) (*Objective, error)
	QueryObjectives(context.Context, *ObjectiveQueryParam) (*ObjectiveQueryResponse, error)
	GetLeaderboard(context.Context, *LeaderboardQueryParam) (*Leaderboard, error)
	mustEmbedUnimplementedObjectiveServiceServer()
}

// UnimplementedObjectiveServiceServer must be embedded to have forward compatible implementations.
type UnimplementedObjectiveServiceServer struct {
}

func (UnimplementedObjectiveServiceServer) RegisterObjective(context.Context, *Objective) (*Objective, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterObjective not implemented")
}
func (UnimplementedObjectiveServiceServer) QueryObjectives(context.Context, *ObjectiveQueryParam) (*ObjectiveQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryObjectives not implemented")
}
func (UnimplementedObjectiveServiceServer) GetLeaderboard(context.Context, *LeaderboardQueryParam) (*Leaderboard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedObjectiveServiceServer) mustEmbedUnimplementedObjectiveServiceServer() {}

// UnsafeObjectiveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectiveServiceServer will
// result in compilation errors.
type UnsafeObjectiveServiceServer interface {
	mustEmbedUnimplementedObjectiveServiceServer()
}

func RegisterObjectiveServiceServer(s grpc.ServiceRegistrar, srv ObjectiveServiceServer) {
	s.RegisterService(&ObjectiveService_ServiceDesc, srv)
}

func _ObjectiveService_RegisterObjective_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Objective)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectiveServiceServer).RegisterObjective(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objective.ObjectiveService/RegisterObjective",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectiveServiceServer).RegisterObjective(ctx, req.(*Objective))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectiveService_QueryObjectives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectiveQueryParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectiveServiceServer).QueryObjectives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objective.ObjectiveService/QueryObjectives",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectiveServiceServer).QueryObjectives(ctx, req.(*ObjectiveQueryParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectiveService_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderboardQueryParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectiveServiceServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objective.ObjectiveService/GetLeaderboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectiveServiceServer).GetLeaderboard(ctx, req.(*LeaderboardQueryParam))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjectiveService_ServiceDesc is the grpc.ServiceDesc for ObjectiveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectiveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "objective.ObjectiveService",
	HandlerType: (*ObjectiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterObjective",
			Handler:    _ObjectiveService_RegisterObjective_Handler,
		},
		{
			MethodName: "QueryObjectives",
			Handler:    _ObjectiveService_QueryObjectives_Handler,
		},
		{
			MethodName: "GetLeaderboard",
			Handler:    _ObjectiveService_GetLeaderboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lib/assets/objective/objective.proto",
}
