name: Dependencies
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  updates:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - orchestrator-server
          - orchestrator-chaincode
          - orchestrator-chaincode-init
    steps:
      - uses: actions/checkout@v3

      - uses: owkin/docker-dependency-updater@v1
        with:
          dockerfile: ./docker/${{matrix.dockerfile }}/Dockerfile
          dependencies: ./docker/${{matrix.dockerfile}}/dependencies.json
          apply: true

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(deps): update apt/apk dependencies in Dockerfile ${{ matrix.dockerfile }}"
          signoff: true
          branch: chore/update-dockerfile-dependencies-${{ matrix.dockerfile }}
          title: "chore(deps): update apt/apk dependencies in Dockerfile ${{ matrix.dockerfile }}"
          body: Updated dependencies.json
          labels: dependencies
          delete-branch: true
          token: ${{ secrets.PAT_DOCKER_DEP_UPDATER }}
          author: "GitHub <noreply@github.com>"
