---
name: Build docker images
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        dockerfile: [orchestrator-server, orchestrator-chaincode, orchestrator-forwarder, orchestrator-rabbitmq-operator, orchestrator-chaincode-init]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: hadolint/hadolint-action@v2.1.0
      with:
        dockerfile: ./docker/${{ matrix.dockerfile }}/Dockerfile

    - name: Set env variables
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "LATEST=true" >> $GITHUB_ENV
          echo "LATEST is set to true"
          echo "VERSION=latest+`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        else
          echo "LATEST=false" >> $GITHUB_ENV
          echo "LATEST is set to false"
          echo "VERSION=`echo $GITHUB_REF | cut -d / -f 3`+`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        fi

    - name: Login to GCR
      uses: docker/login-action@v1
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Docker metadata
      id: docker-metadata
      uses: docker/metadata-action@v3
      with:
        images: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{matrix.dockerfile}}'
        flavor: |
          latest=${{ env.LATEST }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.event_name != 'pull_request' }}
        file: ./docker/${{ matrix.dockerfile }}/Dockerfile
        context: .
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
        build-args: VERSION=${{ env.VERSION }}
