name: Docker build
on:
  workflow_dispatch:
  push:
    branches: [main]
  release:
    types: [published, edited]
  pull_request:
    branches: [main]

concurrency: 
  group: "${{ github.workflow_ref }} - ${{ github.ref }} - ${{ github.event_name }}"
  cancel-in-progress: true

jobs:
  b:
    strategy:
      matrix:
        images: [orchestrator-server, orchestrator-chaincode, orchestrator-chaincode-init]
    uses: substra/substra-gha-workflows/.github/workflows/docker-build.yaml@main
    with:
      image: ${{ matrix.images }}