---
name: Build docker images

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

concurrency:
  # Cancel previous workflows on branch push
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  build:
    strategy:
      matrix:
        dockerfile: [orchestrator-server, orchestrator-chaincode, orchestrator-chaincode-init]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./docker/${{ matrix.dockerfile }}/Dockerfile

    - name: Set env variables
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "LATEST=true" >> $GITHUB_ENV
          echo "LATEST is set to true"
          echo "VERSION=latest+`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        else
          echo "LATEST=false" >> $GITHUB_ENV
          echo "LATEST is set to false"
          echo "VERSION=`echo $GITHUB_REF | cut -d / -f 3`+`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        fi

    - name: Login to registry
      uses: docker/login-action@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker metadata
      id: docker-metadata
      uses: docker/metadata-action@v4
      with:
        images: '${{ env.REGISTRY }}/substra/${{matrix.dockerfile}}'
        flavor: |
          latest=${{ env.LATEST }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: ${{ github.event_name != 'pull_request' }}
        file: ./docker/${{ matrix.dockerfile }}/Dockerfile
        context: .
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
        build-args: VERSION=${{ env.VERSION }}
