---
name: Publish image on GCR
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        docker-image: [server, chaincode, forwarder, rabbitmq-operator]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set env variables
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ]; then
          echo "LATEST=true" >> $GITHUB_ENV
          echo "LATEST is set to true"
        else
          echo "LATEST=false" >> $GITHUB_ENV
          echo "LATEST is set to false"
        fi

    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure docker for GCP
      run: gcloud auth configure-docker

    - name: Docker metadata
      id: docker-metadata
      uses: docker/metadata-action@v3
      with:
        images: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/orchestrator-${{matrix.docker-image}}'
        flavor: |
          latest=${{ env.LATEST }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./docker/${{ matrix.docker-image }}/Dockerfile
        context: .
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
