name: Build and test

on:
  push:
    branches:
    - main
  pull_request:

env:
    GO111MODULE: on

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: build-${{ hashFiles('**/go.sum') }}
      - name: Install protobuf codegen tool
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip
          unzip protoc-3.14.0-linux-x86_64.zip -d $HOME/.local
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install go tools
        run: |
          cd /tmp
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0
          go install github.com/vektra/mockery/v2@v2.13.1
      - name: Build
        run: make
      - name: Test
        run: make test
