name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

env:
  GO111MODULE: on

concurrency:
  # Cancel previous workflows on branch push
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: build-${{ hashFiles('**/go.sum') }}
      - name: Install protobuf codegen tool
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip
          unzip protoc-3.14.0-linux-x86_64.zip -d $HOME/.local
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install go tools
        run: |
          cd /tmp
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0
          go install github.com/vektra/mockery/v2@v2.36.0
      - name: Build
        run: make codegen mocks
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2
          skip-pkg-cache: true
