name: Helm

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
  pull_request:
    branches:
      - main
    paths:
      - "charts/**"
  workflow_dispatch: {}

concurrency:
  # Cancel previous workflows on branch push
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-generate-publish:
    uses: substra/substra-gha-workflows/.github/workflows/helm.yml@main
    secrets: inherit
    with:
      helm-repositories: '[{"name": "bitnami", "url": "https://charts.bitnami.com/bitnami"}]'