name: Helm

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
  pull_request:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3.0
        with:
          version: "v3.5.0"
        id: install
      - name: Build dependencies
        run: helm dep update charts/orchestrator
      - name: Lint Chart
        run: helm lint charts/orchestrator

  generate-chart-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execute readme-generator-for-helm
        run: make docs-charts
      - name: Check diff
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          else
            echo "There should be no change generated, please run 'make docs-charts' to update the chart README.md"
            git diff
            exit 1
          fi

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - test
      - generate-chart-readme
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3.0
        with:
          version: "v3.5.0"
        id: install
      - name: Install tools
        run: |
          sudo snap install yq
          helm plugin install https://github.com/chartmuseum/helm-push
      - name: Add dependencies repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Package chart
        env:
          HARBOR_AUTH_TOKEN: ${{ secrets.HARBOR_AUTH_TOKEN }}
          HARBOR_AUTH_USER: "robot$connect-orchestrator+connect-orchestrator-pusher"
        run: |
          helm dep build charts/orchestrator
          helm package charts/orchestrator
          helm repo add --username=$HARBOR_AUTH_USER --password=$HARBOR_AUTH_TOKEN owkin-priv https://core.harbor.tooling.owkin.com/chartrepo/connect-orchestrator
          helm cm-push orchestrator-$(yq eval .version charts/orchestrator/Chart.yaml).tgz owkin-priv
